# Generated by Django 3.1.6 on 2021-05-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20210527_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
